
Colleges =[{"college": "McGill University",
                    "course": "Math 222: Multivariable calculus",
                    "time" : "10:00 am",
                    "time2" : "11:00 am",
                    "time3" : "12:00 pm",
                    "time4" : "1:00 pm",
                    "time5" : "2:00 pm",
                    "date" : "Tuesday's and Thursday's" ,
                    "location": "Le James McGill Bookstore"},
{"college":"University of Michgan", 
                        "course": "CS 101: Intro to CS" ,
                        "time" : "7:30 am",
                        "time1" : "8:30 am",
                        "time2" : "9:30 am",
                        "time3" : "10:30 am",
                        "time4" : "11:30 am",
                        "time5" : "12:30 pm",
                        "date" : "Wednesday's Friday's" ,
                        "location": "Gerlad R. Ford Presidental Library, Willam L. Clements Library"},
{"college":"Hunter",
                    "course": "Pre 101: Precalculus" ,
                    "time" : "10:30 am",
                    "time2" : "12:30 pm",
                    "time3" : "2:30 pm",
                    "time4" : "4:30 pm",
                    "time5" : "6:30 pm",
                    "date" : "Monday's and Thursdays" ,
                    "location": "Leon & Toby Cooperman Library"},

{"college": "Hunter",
                    "course": "WGS 10000 : Women Gender Studies" ,
                    "time" : "7:30 am",
                    "time2": "8:30 am",
                    "time3": "9:30 am",
                    "time4": "10:30 am",
                    "time5": "11:30 am",
                    "date" : "Wednesday's and Friday's" ,
                    "location": "Leon & Toby Cooperman Library"},
{"college":"City",
                "course": "PHIL 20100 - Philosophy",
                "time" : "7:30 am",
                "time2": "9:30 am",
                "time3": "10:30 am",
                "time4": "11:30 am",
                "time5": "12:30 am",
                "date" : "Tuesday's and Thursday's" ,
                "location": "Cohen Library"},
{"college": "Baruch", 
            "course": "CIS 2300" ,
            "time" : "11:30 am" ,
            "time2" : "2:30 pm",
            "time3" : "4:30 pm",
            "time4" : "6:30 pm",
            "time5" : "8:30pm",
            "date" : "Tuesday's and Thursday's" ,
            "location": "Newman Library"},

{"college" : "Harvard",
            "course": "CS50: Intro to CS" ,
            "time" : "7:30 am" ,
            "time2": "8:30 am",
            "time3": "9:30 am",
            "time4": "10:30 am",
            "time5": "12:30 pm",
            "date" : "Monday's Wednesday's Friday's" ,
            "location": "Widener Library , Lamont Library"},
{"college": "BMCC",
            "course": "CSC 101: Intro to CS" ,
            "time" : "11:30 am",
            "time2": "2:30 pm",
            "time3": "4:30 pm",
            "time4": "6:30 pm",
            "time5": "10:30 pm",
            "date" : "Tuesday's Thursday's" ,
            "location": "A.Philp Randolph Library"},
        
{"college":"City Tech","course": 
            "MAT 1375: Precalculus" ,
            "time" : "11:30 am",
            "time2": "4:30 pm",
            "time3": "6:30 pm",
            "time4": "8:30 pm",
            "time5": "10:30 pm",
            "date" : "Monday's and Wednesday's " ,
            "location": "Ursula C. Schwerin Library"} ,
{"college":"City Tech",
            "course": "MAT 1475 Calculus" ,
            "time" : "7:30 am" ,
            "time2": "8:30 am",
            "time3": "9:30 am",
            "time4": "10:30 am",
            "time5": "1:30 pm",
             "date" : "Thursday's and Tuesday's" ,
            "location": "Ursula C. Schwerin Library"},
{"college":"Utica",
            "course": "CRJ 333: Information Security" ,
            "time" : "10:30 am" ,
            "time2": "12:30 pm",
            "time3": "2:30 pm",
            "time4": "4:30 pm",
            "time5": "6:30 pm",
            "date" : " Tuesday's and Thursday's" ,
            "location": "Frank E. Gannett Memorial Library"},
{"college":"Brown University",
            "course": "Math 0350: Multivariable Calculus " ,
            "time" : "7:30 am" ,
            "time2": "8:30 am",
            "time3": "9:30 am",
            "time4": "10:30 am",
            "time5": "11:30 am",
            "date" : "Monday's, Wednesday's,Friday's " ,
            "location": "John Carter Brown Library,John D. Rockefeller Jr Library "},
{"college":"Babson",
            "course": "DES 3600: Design and System Thinking" ,
            "time" : "9:30 am" ,
            "time2": "10:30 am",
            "time3": "11:30 am",
            "time4": "1:30 pm",
            "time5": "3:30 pm",
            "date" : "Monday's and Wednesday's " ,
            "location": "Horn Library"},
{"college":"Howard University",
            "course": "HIST 005/006 Intro to Black Diaspora" ,
            "time" : "10:30 am" ,
            "time2": "12:30 am",
            "time3": "2:30 pm",
            "time4": "4:30 pm",
            "time5": "6:30 pm",
            "date" : "Thursday's and Tuesday's" ,
            "location": "Founders Library, School of Divinity Collection at HU Law Library"},
{"college":"Columbia",
            "course": "Calculus 2" ,
            "time" : "7:30 am" ,
            "time2": "8:30 am",
            "time3": "9:30 am",
            "time4": "10:30 am",
            "time5": "12:30 am",
            "date" : "Monday's and Friday's" ,
            "location": "Butler Library"},
{"college":"Columbia",
                    "course": "COMS W1004:Intro to CS" ,
                    "time" : "12:30 pm" ,
                    "time2": "1:30 pm",
                    "time3": "2:30 pm",
                    "time4": "4:30 pm",
                    "time5": "8:30 pm",
                    "date" : "Monday's and Thursdays" ,
                    "location": "Leon & Toby Cooperman Library"}]

            

def search(college,course):
    for x in Colleges:
        if course in x['course']:
            return x